[pytest]
addopts =
    -p no:warnings
    -sv
    --only-rerun TimeoutException
    --only-rerun HTTPSConnectionPool
    --only-rerun StaleElementReferenceException
    --only-rerun InvalidSessionIdException
markers =
    smoke: mark test as a hubs test
    regress: mark test as a subscriptions test
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning
    ignore::RuntimeWarning
